### ISSUE TITLE
백엔드 API의 명확한 정의 및 기능 개선

### ISSUE THREAD

**Issue by hankn01** [oidc-soma/aerosquirrel#26]
### 한 줄 설명

프론트엔드 백엔드간 연동 과정에서 백엔드 API의 추상적인 정의나 정의되지 않은 API를 명확하게 정의하고, 실제 사용 가능한 수준으로 기능 개선이 필요합니다.

### 상세 설명

1. LoginUser의 token 값 반환이 필요(Password가 틀렸을 때와 구분 필요)
2. GetAllResources API에서 현재 로그인한 세션을 통해 인증 필요(Header나 body에 session 값을 받는 등의 방법) - FilterResources, GetSingleResource API도 여기에 포함됩니다.
3. CSP 설정 가져오기 및 CSP 설정 업데이트 부분에도 인증 과정이 필요합니다.

**Comment by krapie** [comment]
인증 관련 부분과 API는 이번주 안에 해결해서 마무리 해야 될 것 같네요.
주말에 논의해봐요.

**Comment by hankn01** [comment]
7월 30일(일) Google Meet를 통해 논의하도록 하겠습니다.

**Comment by krapie** [comment]
논의 이후 Postman에 누락된 사항까지 포함하여 최신화하여, 문서로 남기는 방향으로 설정되었습니다.
