### ISSUE TITLE
리소스 인벤토리 API 개발

### ISSUE THREAD

**Issue by mye280c37** [oidc-soma/aerosquirrel#9]
리소스 인벤토리 API 개발
- 리소스 스키마 정의
- 리소스 CRUD API 생성

**Comment by mye280c37** [comment]
추가 논의사항

1. Tag Structure
    * {Key, Value}로 이루어진 Tag structure
    * map
2. Filter Resources 범위
    * request 한 번에 하나의 tag key-value에 대해 filtering
    * request 쿼리로 여러 개의 key-value tags에 대해 resources filtering (and? or?)
    * tag뿐만 아니라 다른 field에 대한 filtering

**Comment by krapie** [comment]
1. 제안 주신 것 처럼, `{key, value}` 형식의 map 자료구조로, tag를 구성하면 좋을 것 같아요.
2. `region`, `type`, `tag` 등 여러 필드에 대해 필터링을 할 수 있어야 세부적으로 리소스들을 분류하고 확인 할 수 있어서, 최대한 많은 필드에 대해 필러팅이 가능했으면 좋겠어요.

**Comment by mye280c37** [comment]
2번 반영해서 filtering 기능 수정하겠습니다.
